name: dsa_palwal_app
description: DSA Palwal Learning App
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  http: ^1.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true
